// <auto-generated />
using System;
using System.Collections.Generic;
using HobbyTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HobbyTracker.Api.Data.Migrations
{
    [DbContext(typeof(HobbyTrackerDbContext))]
    [Migration("20260824201533_AddHltbAllStylesHours")]
    partial class AddHltbAllStylesHours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HobbyTracker.Api.Domain.AuthIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_user_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_identities_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_identities_provider_provider_user_id");

                    b.ToTable("auth_identities", (string)null);
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_hobby_lu");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_hobby_lu_name");

                    b.ToTable("hobby_lu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "games"
                        },
                        new
                        {
                            Id = 2,
                            Name = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "tv"
                        },
                        new
                        {
                            Id = 4,
                            Name = "anime"
                        },
                        new
                        {
                            Id = 5,
                            Name = "books"
                        },
                        new
                        {
                            Id = 6,
                            Name = "music"
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("HoursPlayed")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hours_played");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_log_entries_media_id");

                    b.HasIndex("UserId", "MediaId")
                        .HasDatabaseName("ix_log_entries_user_id_media_id");

                    b.ToTable("log_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_log_entries_hours_played_range", "hours_played IS NULL OR (hours_played > 0 AND hours_played <= 999.99)");

                            t.HasCheckConstraint("ck_log_entries_rating_range", "rating IS NULL OR (rating >= 1.0 AND rating <= 10.0)");

                            t.HasCheckConstraint("ck_log_entries_timestamp_order", "started_at IS NULL OR completed_at IS NULL OR completed_at >= started_at");
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_url");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<int>("HobbyId")
                        .HasColumnType("integer")
                        .HasColumnName("hobby_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("HobbyId")
                        .HasDatabaseName("ix_media_hobby_id");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_media_source_id_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.ToTable("media", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<int>("LogEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("log_entry_id");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("LogEntryId", "WrittenAt")
                        .HasDatabaseName("ix_notes_log_entry_id_written_at");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Source", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_source_lu");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_source_lu_name");

                    b.ToTable("source_lu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://api.igdb.com/v4/",
                            Name = "igdb"
                        },
                        new
                        {
                            Id = 2,
                            Name = "manual"
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Game", b =>
                {
                    b.HasBaseType("HobbyTracker.Api.Domain.Media");

                    b.PrimitiveCollection<List<string>>("Developers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("developers");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<decimal?>("HltbAllStylesHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hltb_all_styles_hours");

                    b.Property<DateTimeOffset?>("HltbCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hltb_checked_at");

                    b.Property<decimal?>("HltbCompletionistHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hltb_completionist_hours");

                    b.Property<int?>("HltbId")
                        .HasColumnType("integer")
                        .HasColumnName("hltb_id");

                    b.Property<decimal?>("HltbMainExtraHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hltb_main_extra_hours");

                    b.Property<decimal?>("HltbMainStoryHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hltb_main_story_hours");

                    b.PrimitiveCollection<List<string>>("Platforms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("platforms");

                    b.Property<string>("PrimaryGenre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_genre");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.ToTable("games", null, t =>
                        {
                            t.HasCheckConstraint("ck_games_hltb_hours_positive", "(hltb_all_styles_hours    IS NULL OR hltb_all_styles_hours    > 0) AND\r\n(hltb_main_story_hours    IS NULL OR hltb_main_story_hours    > 0) AND\r\n(hltb_main_extra_hours    IS NULL OR hltb_main_extra_hours    > 0) AND\r\n(hltb_completionist_hours IS NULL OR hltb_completionist_hours > 0)");

                            t.Property("Id")
                                .HasColumnName("media_id");
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.AuthIdentity", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.User", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.LogEntry", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Media", "Media")
                        .WithMany("LogEntries")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_entries_media_media_id");

                    b.HasOne("HobbyTracker.Api.Domain.User", "User")
                        .WithMany("LogEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_entries_users_user_id");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Media", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Hobby", "Hobby")
                        .WithMany("Media")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_hobby_lu_hobby_id");

                    b.HasOne("HobbyTracker.Api.Domain.Source", "Source")
                        .WithMany("Media")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_source_lu_source_id");

                    b.Navigation("Hobby");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Note", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.LogEntry", "LogEntry")
                        .WithMany("Notes")
                        .HasForeignKey("LogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_log_entries_log_entry_id");

                    b.Navigation("LogEntry");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Game", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Media", null)
                        .WithOne()
                        .HasForeignKey("HobbyTracker.Api.Domain.Game", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_media_id");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Hobby", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.LogEntry", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Media", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Source", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.User", b =>
                {
                    b.Navigation("AuthIdentities");

                    b.Navigation("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
