// <auto-generated />
using System;
using System.Collections.Generic;
using HobbyTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HobbyTracker.Api.Data.Migrations
{
    [DbContext(typeof(HobbyTrackerDbContext))]
    partial class HobbyTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HobbyTracker.Api.Domain.AuthIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_user_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_identities_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_identities_provider_provider_user_id");

                    b.ToTable("auth_identities", (string)null);
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_hobby_lu");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_hobby_lu_name");

                    b.ToTable("hobby_lu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "games"
                        },
                        new
                        {
                            Id = 2,
                            Name = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "tv"
                        },
                        new
                        {
                            Id = 4,
                            Name = "anime"
                        },
                        new
                        {
                            Id = 5,
                            Name = "books"
                        },
                        new
                        {
                            Id = 6,
                            Name = "music"
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<decimal?>("HoursPlayed")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hours_played");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rating");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_log_entries_media_id");

                    b.HasIndex("UserId", "MediaId")
                        .HasDatabaseName("ix_log_entries_user_id_media_id");

                    b.ToTable("log_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_log_entries_episode_range", "episode_number IS NULL OR episode_number >= 1");

                            t.HasCheckConstraint("ck_log_entries_hours_played_range", "hours_played IS NULL OR (hours_played > 0 AND hours_played <= 999.99)");

                            t.HasCheckConstraint("ck_log_entries_rating_range", "rating IS NULL OR (rating >= 1.0 AND rating <= 10.0)");

                            t.HasCheckConstraint("ck_log_entries_season_range", "season_number IS NULL OR season_number >= 0");

                            t.HasCheckConstraint("ck_log_entries_timestamp_order", "started_at IS NULL OR completed_at IS NULL OR completed_at >= started_at");
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_url");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<int>("HobbyId")
                        .HasColumnType("integer")
                        .HasColumnName("hobby_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("HobbyId")
                        .HasDatabaseName("ix_media_hobby_id");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_media_source_id_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.ToTable("media", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<int>("LogEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("log_entry_id");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("LogEntryId", "WrittenAt")
                        .HasDatabaseName("ix_notes_log_entry_id_written_at");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Source", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_source_lu");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_source_lu_name");

                    b.ToTable("source_lu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://api.igdb.com/v4/",
                            Name = "igdb"
                        },
                        new
                        {
                            Id = 2,
                            Name = "manual"
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://api.themoviedb.org/3/",
                            Name = "tmdb"
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://api.themoviedb.org/3/tv/",
                            Name = "tmdb-tv"
                        },
                        new
                        {
                            Id = 5,
                            BaseUrl = "https://api.myanimelist.net/v2/",
                            Name = "mal"
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.TvSeason", b =>
                {
                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("episode_count");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("MediaId", "SeasonNumber")
                        .HasName("pk_tv_seasons");

                    b.ToTable("tv_seasons", null, t =>
                        {
                            t.HasCheckConstraint("ck_tv_seasons_episode_count", "episode_count >= 0");

                            t.HasCheckConstraint("ck_tv_seasons_season_number", "season_number >= 0");
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Anime", b =>
                {
                    b.HasBaseType("HobbyTracker.Api.Domain.Media");

                    b.Property<string>("AirStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("air_status");

                    b.Property<string>("EnglishTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("english_title");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("episode_count");

                    b.Property<int?>("EpisodeRuntimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("episode_runtime_seconds");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<decimal?>("MeanScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("mean_score");

                    b.Property<string>("MediaType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("PrimaryGenre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_genre");

                    b.Property<string>("SourceMaterial")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_material");

                    b.Property<string>("StartSeason")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("start_season");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.PrimitiveCollection<List<string>>("Studios")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("studios");

                    b.Property<int?>("TotalRuntimeMinutes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("total_runtime_minutes")
                        .HasComputedColumnSql("episode_count * episode_runtime_seconds / 60", true);

                    b.ToTable("anime", null, t =>
                        {
                            t.HasCheckConstraint("ck_anime_counts_positive", "(episode_count IS NULL OR episode_count > 0)\nAND (episode_runtime_seconds IS NULL OR episode_runtime_seconds > 0)");

                            t.HasCheckConstraint("ck_anime_mean_score_range", "mean_score IS NULL OR (mean_score >= 1.0 AND mean_score <= 10.0)");

                            t.Property("Id")
                                .HasColumnName("media_id");
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Game", b =>
                {
                    b.HasBaseType("HobbyTracker.Api.Domain.Media");

                    b.PrimitiveCollection<List<string>>("Developers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("developers");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<decimal?>("HltbAllStylesHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hltb_all_styles_hours");

                    b.Property<DateTimeOffset?>("HltbCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hltb_checked_at");

                    b.Property<decimal?>("HltbCompletionistHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hltb_completionist_hours");

                    b.Property<int?>("HltbId")
                        .HasColumnType("integer")
                        .HasColumnName("hltb_id");

                    b.Property<decimal?>("HltbMainExtraHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hltb_main_extra_hours");

                    b.Property<decimal?>("HltbMainStoryHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hltb_main_story_hours");

                    b.PrimitiveCollection<List<string>>("Platforms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("platforms");

                    b.Property<string>("PrimaryGenre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_genre");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.ToTable("games", null, t =>
                        {
                            t.HasCheckConstraint("ck_games_hltb_hours_positive", "(hltb_all_styles_hours    IS NULL OR hltb_all_styles_hours    > 0) AND\r\n(hltb_main_story_hours    IS NULL OR hltb_main_story_hours    > 0) AND\r\n(hltb_main_extra_hours    IS NULL OR hltb_main_extra_hours    > 0) AND\r\n(hltb_completionist_hours IS NULL OR hltb_completionist_hours > 0)");

                            t.Property("Id")
                                .HasColumnName("media_id");
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Movie", b =>
                {
                    b.HasBaseType("HobbyTracker.Api.Domain.Media");

                    b.PrimitiveCollection<List<string>>("Directors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("directors");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<string>("PrimaryGenre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_genre");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.ToTable("movies", null, t =>
                        {
                            t.HasCheckConstraint("ck_movies_runtime_positive", "runtime_minutes IS NULL OR runtime_minutes > 0");

                            t.Property("Id")
                                .HasColumnName("media_id");
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.TvShow", b =>
                {
                    b.HasBaseType("HobbyTracker.Api.Domain.Media");

                    b.Property<string>("AirStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("air_status");

                    b.PrimitiveCollection<List<string>>("Creators")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("creators");

                    b.Property<int?>("EpisodeRuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("episode_runtime_minutes");

                    b.Property<int?>("FirstAirYear")
                        .HasColumnType("integer")
                        .HasColumnName("first_air_year");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<int?>("LastAirYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_air_year");

                    b.Property<int?>("NumberOfEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_episodes");

                    b.Property<int?>("NumberOfSeasons")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_seasons");

                    b.Property<string>("PrimaryGenre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_genre");

                    b.Property<int?>("TotalRuntimeMinutes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("total_runtime_minutes")
                        .HasComputedColumnSql("number_of_episodes * episode_runtime_minutes", true);

                    b.ToTable("tv_shows", null, t =>
                        {
                            t.HasCheckConstraint("ck_tv_shows_counts_positive", "(number_of_seasons IS NULL OR number_of_seasons > 0)\r\nAND (number_of_episodes IS NULL OR number_of_episodes > 0)");

                            t.HasCheckConstraint("ck_tv_shows_episode_runtime_positive", "episode_runtime_minutes IS NULL OR episode_runtime_minutes > 0");

                            t.HasCheckConstraint("ck_tv_shows_year_span", "first_air_year IS NULL OR last_air_year IS NULL OR last_air_year >= first_air_year");

                            t.Property("Id")
                                .HasColumnName("media_id");
                        });
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.AuthIdentity", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.User", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.LogEntry", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Media", "Media")
                        .WithMany("LogEntries")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_entries_media_media_id");

                    b.HasOne("HobbyTracker.Api.Domain.User", "User")
                        .WithMany("LogEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_entries_users_user_id");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Media", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Hobby", "Hobby")
                        .WithMany("Media")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_hobby_lu_hobby_id");

                    b.HasOne("HobbyTracker.Api.Domain.Source", "Source")
                        .WithMany("Media")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_source_lu_source_id");

                    b.Navigation("Hobby");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Note", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.LogEntry", "LogEntry")
                        .WithMany("Notes")
                        .HasForeignKey("LogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_log_entries_log_entry_id");

                    b.Navigation("LogEntry");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.TvSeason", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.TvShow", "Show")
                        .WithMany("Seasons")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tv_seasons_tv_shows_media_id");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Anime", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Media", null)
                        .WithOne()
                        .HasForeignKey("HobbyTracker.Api.Domain.Anime", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anime_media_id");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Game", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Media", null)
                        .WithOne()
                        .HasForeignKey("HobbyTracker.Api.Domain.Game", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_media_id");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Movie", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Media", null)
                        .WithOne()
                        .HasForeignKey("HobbyTracker.Api.Domain.Movie", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_media_id");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.TvShow", b =>
                {
                    b.HasOne("HobbyTracker.Api.Domain.Media", null)
                        .WithOne()
                        .HasForeignKey("HobbyTracker.Api.Domain.TvShow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tv_shows_media_id");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Hobby", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.LogEntry", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Media", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.Source", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.User", b =>
                {
                    b.Navigation("AuthIdentities");

                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("HobbyTracker.Api.Domain.TvShow", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
