using HobbyTracker.Api.Data;
using HobbyTracker.Api.Domain;
using HobbyTracker.Api.Integrations.Tmdb;
using HobbyTracker.Api.Services;
using HobbyTracker.Api.Tests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace HobbyTracker.Api.Tests.Services;

/// <summary>
/// TMDB into the database and back out, for shows.
///
/// <see cref="Services.MovieCatalogServiceTests"/>'s sibling, and the differences between them
/// are differences between a film and a show rather than between two ways of writing a service:
/// a show has seasons that must be replaced rather than merged, an episode runtime with a
/// fallback behind it, and a source row of its own.
/// </summary>
[Collection(DatabaseCollection.Name)]
public sealed class TvCatalogServiceTests(PostgresFixture postgres) : DatabaseTestBase(postgres)
{
    [Fact]
    public async Task Searching_stores_what_search_knows_and_no_more()
    {
        Tmdb.SetTvResults(
            "breaking bad",
            FakeTmdbClient.Show(1396, "Breaking Bad", "2008-01-20", "/poster.jpg", 14_000));

        await WithDbAsync(db => CreateService(db).SearchAsync("breaking bad", null, Ct));

        var show = await WithDbAsync(db => db.TvShows.SingleAsync(Ct));

        show.Title.ShouldBe("Breaking Bad");
        show.ExternalId.ShouldBe("1396");
        show.HobbyId.ShouldBe(SeedData.Hobbies.Tv);

        // The source row that keeps TMDB film 1396 and TMDB show 1396 apart.
        show.SourceId.ShouldBe(SeedData.Sources.TmdbTv);

        show.FirstAirYear.ShouldBe(2008);
        show.CoverUrl.ShouldBe("https://image.tmdb.org/t/p/w342/poster.jpg");

        // None of this is on /search/tv, so writing it here would mean writing empties over
        // whatever enrichment had already fetched, on the next search anybody typed.
        show.NumberOfSeasons.ShouldBeNull();
        show.NumberOfEpisodes.ShouldBeNull();
        show.EpisodeRuntimeMinutes.ShouldBeNull();
        show.Genres.ShouldBeEmpty();
        show.Creators.ShouldBeEmpty();
        show.Seasons.ShouldBeEmpty();
    }

    [Fact]
    public async Task Searching_the_same_thing_twice_does_not_duplicate_a_show()
    {
        Tmdb.SetTvResults("breaking bad", FakeTmdbClient.Show(1396, "Breaking Bad"));

        await WithDbAsync(db => CreateService(db).SearchAsync("breaking bad", null, Ct));
        await WithDbAsync(db => CreateService(db).SearchAsync("breaking bad", null, Ct));

        (await WithDbAsync(db => db.Media.CountAsync(Ct))).ShouldBe(1);
    }

    [Fact]
    public async Task Enriching_fills_in_everything_the_detail_call_knows()
    {
        var mediaId = await GivenAStoredShowAsync();

        Tmdb.TvById[1396] = FakeTmdbClient.ShowDetail(
            1396,
            "Breaking Bad",
            firstAirDate: "2008-01-20",
            lastAirDate: "2013-09-29",
            status: "Ended",
            seasons: 5,
            episodes: 62,
            episodeRunTime: [45],
            genres: ["Crime", "Drama"],
            creators: ["Vince Gilligan"],
            seasonList: [(0, 8, "Specials"), (1, 7, "Season 1"), (2, 13, "Season 2")]);

        (await WithDbAsync(db => CreateService(db).EnrichAsync(mediaId, Ct))).ShouldBeTrue();

        var show = await WithDbAsync(db => db.TvShows
            .Include(candidate => candidate.Seasons)
            .SingleAsync(Ct));

        show.FirstAirYear.ShouldBe(2008);
        show.LastAirYear.ShouldBe(2013);
        show.AirStatus.ShouldBe("Ended");
        show.NumberOfSeasons.ShouldBe(5);
        show.NumberOfEpisodes.ShouldBe(62);
        show.EpisodeRuntimeMinutes.ShouldBe(45);
        show.Genres.ShouldBe(["Crime", "Drama"]);
        show.Creators.ShouldBe(["Vince Gilligan"]);

        show.Seasons.OrderBy(season => season.SeasonNumber)
            .Select(season => (season.SeasonNumber, season.EpisodeCount))
            .ShouldBe([(0, 8), (1, 7), (2, 13)]);

        // Generated by Postgres from the two counts above, never written by this service.
        show.TotalRuntimeMinutes.ShouldBe(2790);
    }

    [Fact]
    public async Task Refreshing_replaces_the_seasons_rather_than_adding_to_them()
    {
        // The quiet one. Seasons are replaced wholesale on every refresh, so a show that loses a
        // season upstream must lose it here — and if the collection is not loaded first, Clear()
        // removes nothing, the adds collide with the composite key, and the upsert's 23505
        // recovery would read that as a concurrent insert and move on with stale seasons.
        var mediaId = await GivenAStoredShowAsync();

        Tmdb.TvById[1396] = FakeTmdbClient.ShowDetail(
            1396, "Breaking Bad", seasonList: [(1, 7, "Season 1"), (2, 13, "Season 2")]);

        await WithDbAsync(db => CreateService(db).EnrichAsync(mediaId, Ct));

        // Upstream re-cuts the show: season 2 is gone and season 1 is longer.
        Tmdb.TvById[1396] = FakeTmdbClient.ShowDetail(
            1396, "Breaking Bad", seasonList: [(1, 9, "Season 1")]);

        await WithDbAsync(db => CreateService(db).EnrichAsync(mediaId, Ct));

        var seasons = await WithDbAsync(db => db.Set<TvSeason>().OrderBy(s => s.SeasonNumber).ToListAsync(Ct));

        seasons.Count.ShouldBe(1);
        seasons[0].SeasonNumber.ShouldBe(1);
        seasons[0].EpisodeCount.ShouldBe(9);
    }

    [Fact]
    public async Task An_episode_runtime_falls_back_to_the_last_episode_that_aired()
    {
        // TMDB has been dropping episode_run_time on newer shows, so this branch is the normal
        // path for anything recent rather than a defensive corner.
        var mediaId = await GivenAStoredShowAsync();

        Tmdb.TvById[1396] = FakeTmdbClient.ShowDetail(
            1396, "Severance", episodeRunTime: [], lastEpisodeRuntime: 47);

        await WithDbAsync(db => CreateService(db).EnrichAsync(mediaId, Ct));

        (await WithDbAsync(db => db.TvShows.SingleAsync(Ct))).EpisodeRuntimeMinutes.ShouldBe(47);
    }

    [Fact]
    public async Task An_episode_runtime_of_nought_becomes_null_rather_than_a_lie()
    {
        var mediaId = await GivenAStoredShowAsync();

        Tmdb.TvById[1396] = FakeTmdbClient.ShowDetail(
            1396, "Breaking Bad", episodeRunTime: [0], lastEpisodeRuntime: 0);

        await WithDbAsync(db => CreateService(db).EnrichAsync(mediaId, Ct));

        var show = await WithDbAsync(db => db.TvShows.SingleAsync(Ct));

        show.EpisodeRuntimeMinutes.ShouldBeNull();
        show.TotalRuntimeMinutes.ShouldBeNull();
    }

    [Fact]
    public async Task Enriching_never_touches_the_genre_somebody_chose()
    {
        var mediaId = await GivenAStoredShowAsync();

        await WithDbAsync(async db =>
        {
            var show = await db.TvShows.SingleAsync(Ct);
            show.PrimaryGenre = "Drama";
            await db.SaveChangesAsync(Ct);
        });

        Tmdb.TvById[1396] = FakeTmdbClient.ShowDetail(1396, "Breaking Bad", genres: ["Crime", "Drama"]);

        await WithDbAsync(db => CreateService(db).EnrichAsync(mediaId, Ct));

        (await WithDbAsync(db => db.TvShows.SingleAsync(Ct))).PrimaryGenre.ShouldBe("Drama");
    }

    [Fact]
    public async Task Enriching_something_that_is_not_a_show_asks_tmdb_nothing()
    {
        var mediaId = await GivenMovieAsync("Arrival", externalId: "329865");

        (await WithDbAsync(db => CreateService(db).EnrichAsync(mediaId, Ct))).ShouldBeFalse();

        Tmdb.TvIdLookups.ShouldBeEmpty();
    }

    [Fact]
    public async Task A_show_tmdb_has_forgotten_keeps_what_was_last_known()
    {
        var mediaId = await GivenAStoredShowAsync();

        await WithDbAsync(async db =>
        {
            var show = await db.TvShows.SingleAsync(Ct);
            show.NumberOfEpisodes = 62;
            await db.SaveChangesAsync(Ct);
        });

        // No entry in TvById at all — TMDB has never heard of the id.
        (await WithDbAsync(db => CreateService(db).EnrichAsync(mediaId, Ct))).ShouldBeFalse();

        (await WithDbAsync(db => db.TvShows.SingleAsync(Ct))).NumberOfEpisodes.ShouldBe(62);
    }

    [Fact]
    public async Task Concurrent_identical_searches_still_leave_one_row()
    {
        Tmdb.SetTvResults("breaking bad", FakeTmdbClient.Show(1396, "Breaking Bad"));

        await Task.WhenAll(Enumerable.Range(0, 5).Select(_ =>
            WithDbAsync(db => CreateService(db).SearchAsync("breaking bad", null, Ct))));

        (await WithDbAsync(db => db.Media.CountAsync(Ct))).ShouldBe(1);
    }

    [Fact]
    public async Task Refreshing_only_touches_shows_somebody_logged()
    {
        var logged = await GivenAStoredShowAsync();
        await GivenAStoredShowAsync(externalId: "95396", title: "Severance");

        await GivenLogEntryAsync(logged, LogStatus.InProgress);

        Tmdb.TvById[1396] = FakeTmdbClient.ShowDetail(1396, "Breaking Bad", episodes: 62);

        var refreshed = await WithDbAsync(db => CreateService(db).RefreshLibraryAsync(Ct));

        refreshed.ShouldBe(1);
        Tmdb.TvIdLookups.ShouldBe([1396]);
    }

    private async Task<int> GivenAStoredShowAsync(
        string externalId = "1396", string title = "Breaking Bad")
    {
        return await WithDbAsync(async db =>
        {
            var show = new TvShow
            {
                HobbyId = SeedData.Hobbies.Tv,
                SourceId = SeedData.Sources.TmdbTv,
                ExternalId = externalId,
                Title = title,
            };

            db.TvShows.Add(show);
            await db.SaveChangesAsync(Ct);
            return show.Id;
        });
    }

    private TvCatalogService CreateService(HobbyTrackerDbContext db) => new(
        db,
        Tmdb,
        Options.Create(new TmdbOptions { AccessToken = "token" }),
        NullLogger<TvCatalogService>.Instance,
        new FakeCurrentUser(UserId));
}
